<?php

/**
 * @file
 * Commerce panels integration primary module file.
 *
 * This file contains nothing more than a ctools hook to allow
 * ctools to find the plugins directory.
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param type $owner
 *   The system name of the module owning the plugin type for which a base
 *   directory location is being requested.
 *
 * @param type $plugin_type
 *   The name of the plugin type for which a base directory is being requested.
 *
 * @return path
 *   The path where CTools' plugin system should search for plugin files,
 *   relative to your module's root. Omit leading and trailing slashes.
 */
function commerce_panels_integration_ctools_plugin_directory($owner, $plugin_type) {
dpm(get_defined_vars());
  if ($owner == 'page_manager') {
    return 'plugins/' . $plugin_type;
  }
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
}

function commerce_panels_integration_ctools_plugin_pre_alter(&$plugin, &$info) {
//  dpm(get_defined_vars());
}
